const rules = [
    "Drink at the name of the movie",
    "Drink when someone over/underreacts (as a consensus)",
    "Drink for falling in love",
    "Sip every time the main character's name is said",
    "Drink when you have to read",
    "Drink for old technology",
    "Drink for genuine laughter/tears",
    "Shot for the dead parents",
    "Drink for sacrifice"
];
const images = [
    "dumbo.jpg",
    "avengers.jpg",
    "lion.jpg",
    "hunchback.jpg",
    "deadpool.jpg",
    "hercules.jpg",
    "mickey.jpg",
    "free.jpg",
    "star.jpg",
    "nightmare.jpg",
    "snow.jpg",
    "frozen.jpg"
];
const SLOTS_PER_REEL = 12;
// radius = Math.round( ( panelWidth / 2) / Math.tan( Math.PI / SLOTS_PER_REEL ) ); 
// current settings give a value of 149, rounded to 150
const REEL_RADIUS = 150;
const movies = [
    'Lady and the Tramp',
    'Houellebecq: encore un best-seller?',
    'Apollo: Missions to the Moon',
    'Dumbo',
    'Captain Marvel',
    'The Lost Tomb of Alexander the Great',
    'Kim Possible',
    'Paris to Pittsburgh',
    'Life-Size 2',
    'The Flood',
    'Mission to the Sun',
    'MARS: Inside SpaceX',
    'Marvel Rising: Secret Warriors',
    'Free Solo',
    'Science Fair',
    'Freaky Friday',
    'Rocky Mountain Animal Rescue',
    'Zombies',
    'Decorating Disney: Holiday Magic',
    'Man Among Cheetahs',
    'Titanic: 20 Years Later with James Cameron',
    'Jane',
    'Breaking2',
    'Diana: In Her Own Words',
    'Descendants 2',
    'Earth Live',
    'Cars 3',
    'Tangled: Before Ever After',
    'Disneys Newsies the Broadway Musical',
    'Atlantis Rising',
    'Sea of Hope: Americas Underwater Treasures',
    'Before the Flood',
    'Rogue One: A Star Wars Story',
    'Moana',
    'The Swap',
    'Queen of Katwe',
    'Petes Dragon',
    'The BFG',
    'Finding Dory',
    'Adventures in Babysitting',
    'Ice Age: The Great Egg-Scapade',
    'Zootopia',
    'The Finest Hours',
    'Star Wars: The Force Awakens World Premiere Red Carpet',
    'Wild Yellowstone',
    'The Good Dinosaur',
    'The Lion Guard: Return of the Roar',
    'Invisible Sister',
    'Descendants',
    'Ant-Man',
    'Inside Out',
    'Avengers: Age of Ultron',
    'Monkey Kingdom',
    'Bad Hair Day',
    'Big Hero 6',
    'How to Build a Better Boy',
    'Guardians of the Galaxy',
    'Zapped',
    'Bears',
    'Muppets Most Wanted',
    'Marvel Studios: Assembling a Universe',
    'Cloud 9',
    'Miracle Landing on the Hudson',
    'Saving Mr. Banks',
    'Thor: The Dark World',
    'Sharks of Lost Island',
    'Super Buddies',
    'Teen Beach Movie',
    'Monsters University',
    'Iron Man 3',
    'The Wizards Return: Alex vs. Alex',
    'The Mistle-Tones',
    'Winged Seduction: Birds of Paradise',
    'Santa Paws 2: The Santa Pups',
    'Wreck-It Ralph',
    'Secret of the Wings',
    'Brave',
    'Let It Shine',
    'Chimpanzee',
    'Frenemies',
    '12 Dates of Christmas',
    'Good Luck Charlie, Its Christmas!',
    'The Muppets',
    'Geek Charming',
    'Teen Spirit',
    'Phineas and Ferb the Movie: Across the 2nd Dimension',
    'Winnie the Pooh',
    'Cars 2',
    'Sharpays Fabulous Adventure',
    'Pirates of the Caribbean: On Stranger Tides',
    'African Cats',
    'Lemonade Mouth',
    'The Suite Life Movie',
    'Disneynature: Wings of Life',
    'TRON: Legacy',
    'Tangled',
    'Avalon High',
    'Secretariat',
    'Tinker Bell and the Great Fairy Rescue',
    'Camp Rock 2: The Final Jam',
    'Den Brother',
    'Toy Story 3',
    'Diary of a Wimpy Kid',
    'Alice in Wonderland',
    'StarStruck',
    'Skyrunners',
    'The Princess and the Frog',
    'Tinker Bell and the Lost Treasure',
    'Bizarre Dinosaurs',
    'Wizards of Waverly Place: The Movie',
    'Princess Protection Program',
    'Trail of the Panda',
    'Hatching Pete',
    'Hannah Montana: The Movie',
    'Kingdom of the Blue Whale',
    'Jonas Brothers: The 3D Concert Experience',
    'Dadnapped',
    'The Crimson Wing: Mystery of the Flamingos',
    'Bolt',
    'Tinker Bell',
    'High School Musical 3: Senior Year',
    'The Little Mermaid: Ariels Beginning',
    'The Cheetah Girls: One World',
    'Star Wars: The Clone Wars',
    'WALL·E',
    'Camp Rock',
    'The Chronicles of Narnia: Prince Caspian',
    'Iron Man',
    'College Road Trip',
    'Hannah Montana and Miley Cyrus: Best of Both Worlds Concert',
    'Minutemen',
    'National Treasure: Book of Secrets',
    'Snowglobe',
    'Dan in Real Life',
    'Twitches Too',
    'The Game Plan',
    'High School Musical 2',
    'Ratatouille',
    'The Secret of the Magic Gourd',
    'Johnny Kapahala: Back on Board',
    'Pirates of the Caribbean: At Worlds End',
    'Meet the Robinsons',
    'Jump In!',
    'The Fox and the Hound 2',
    'The Santa Clause 3: The Escape Clause',
    'Flicka',
    'Return to Halloweentown',
    'Brother Bear 2',
    'The Cheetah Girls 2',
    'Invincible',
    'Read It and Weep',
    'Pirates of the Caribbean: Dead Mans Chest',
    'Wendy Wu: Homecoming Warrior',
    'Cars',
    'The Wild',
    'Cow Belles',
    'The Shaggy Dog',
    'Eight Below',
    'Roving Mars',
    'High School Musical',
    'Kronks New Groove',
    'Once Upon a Mattress',
    'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',
    'Chicken Little',
    'Twitches',
    'The Greatest Game Ever Played',
    'The Proud Family Movie',
    'Valiant',
    'Life Is Ruff',
    'Herbie Fully Loaded',
    'Go Figure',
    'Ice Princess',
    'Buffalo Dreams',
    'Millions of Cardinals Memories: Busch Stadium 1966-2005',
    'The Pacifier',
    'Poohs Heffalump Movie',
    'Aliens of the Deep',
    'Now You See It...',
    'Mickeys Twice Upon a Christmas',
    'The Incredibles',
    'Halloweentown High',
    'Empire of Dreams: The Story of the Star Wars Trilogy',
    'Mickey, Donald, Goofy: The Three Musketeers',
    'The Princess Diaries 2: Royal Engagement',
    'Tiger Cruise',
    'Stuck in the Suburbs',
    'Zenon: Z3',
    'Sacred Planet',
    'Home on the Range',
    'Going to the Mat',
    'Confessions of a Teenage Drama Queen',
    'Miracle',
    'Teachers Pet',
    'Pixel Perfect',
    'The Young Black Stallion',
    'Recess: All Growed Down',
    'The Haunted Mansion',
    'Full-Court Miracle',
    'Brother Bear',
    'Deep Blue',
    'The Cheetah Girls',
    'Freaky Friday',
    'Eddies Million Dollar Cook-Off',
    'Pirates of the Caribbean: The Curse of the Black Pearl',
    'The Even Stevens Movie',
    'Finding Nemo',
    'Atlantis: Milos Return',
    'The Lizzie McGuire Movie',
    'Right on Track',
    'Piglets Big Movie',
    'Inspector Gadget 2',
    'The Jungle Book 2',
    'You Wish!',
    'Treasure Planet',
    'Winnie the Pooh: A Very Merry Pooh Year',
    'The Santa Clause 2',
    'Tuck Everlasting',
    'The Scream Team',
    'A Ring of Endless Light',
    'Gotta Kick It Up!',
    'The Country Bears',
    'Get a Clue',
    'Star Wars: Attack of the Clones - A Jigsaw Puzzle',
    'The Rookie',
    'Tru Confessions',
    'Cadet Kelly',
    'Peter Pan 2: Return to Never Land',
    'Double Teamed',
    'Snow Dogs',
    'Three Days',
    'Twas the Night',
    'Monsters, Inc.',
    'Halloweentown II: Kalabars Revenge',
    'The Poof Point',
    'Jumping Ship',
    'The Princess Diaries',
    'The Jennie Project',
    'Atlantis: The Lost Empire',
    'Hounded',
    'The Luck of the Irish',
    'Motocrossed',
    'Recess: Schools Out',
    'Zenon: The Zequel',
    'The Emperors New Groove',
    'The Ultimate Christmas Present',
    '102 Dalmatians',
    'Phantom of the Megaplex',
    'Moms Got a Date with a Vampire',
    'Remember the Titans',
    'The Other Me',
    'Quints',
    'Ready to Run',
    'The Kid',
    'Stepsister from Planet Weird',
    'Dinosaur',
    'Miracle in Lane 2',
    'Rip Girls',
    'Alley Cats Strike',
    'Whispers: An Elephants Tale',
    'An Extremely Goofy Movie',
    'The Tigger Movie',
    'The Color of Friendship',
    'Up, Up, and Away!',
    'Toy Story 2',
    'Horse Sense',
    'Mickeys Once Upon a Christmas',
    'Annie',
    'Dont Look Under the Bed',
    'Genius',
    'Johnny Tsunami',
    'Inspector Gadget',
    'Smart House',
    'The Thirteenth Year',
    'Can of Worms',
    '10 Things I Hate About You',
    'Dougs 1st Movie',
    'My Favorite Martian',
    'Zenon: Girl of the 21st Century',
    'Mighty Joe Young',
    'A Bugs Life',
    'Ill Be Home for Christmas',
    'Richie Richs Christmas Wish',
    'Halloweentown',
    'The Jungle Book: Mowglis Story',
    'Brink!',
    'The Parent Trap',
    'You Lucky Dog',
    'Mulan',
    'The Brave Little Toaster Goes to Mars',
    'Miracle at Midnight',
    'Meet the Deedles',
    'Belles Magical World',
    'Ruby Bridges',
    'Flubber',
    'Beauty and the Beast: The Enchanted Christmas',
    'Poohs Grand Adventure: The Search for Christopher Robin',
    'Hercules',
    'The Brave Little Toaster to the Rescue',
    'Honey, We Shrunk Ourselves!',
    'Jungle 2 Jungle',
    'That Darn Cat',
    '101 Dalmatians',
    'First Kid',
    'Aladdin and the King of Thieves',
    'Jack',
    'Kazaam',
    'The Hunchback of Notre Dame',
    'James And The Giant Peach',
    'Muppet Treasure Island',
    'Tom and Huck',
    'Toy Story',
    'Frank and Ollie',
    'A Kid in King Arthurs Court',
    'Operation Dumbo Drop',
    'Pocahontas',
    'While You Were Sleeping',
    'A Goofy Movie',
    'Tall Tale',
    'Heavyweights',
    'The Santa Clause',
    'The Fantastic Four',
    'Camp Nowhere',
    'The Lion King',
    'Aladdin and the Return of Jafar',
    'Thumbelina',
    'Blank Check',
    'Iron Will',
    'Sister Act 2: Back in the Habit',
    'The Three Musketeers',
    'The Nightmare Before Christmas',
    'Hocus Pocus',
    'Rookie of the Year',
    'Life with Mikey',
    'The Sandlot',
    'The Adventures of Huck Finn',
    'The Muppet Christmas Carol',
    'Aladdin',
    'Honey, I Blew Up the Kid',
    'Sister Act',
    'Newsies',
    'Beauty and the Beast',
    'The Rocketeer',
    'White Fang',
    'The Rescuers Down Under',
    'DuckTales the Movie: Treasure of the Lost Lamp',
    'The Little Mermaid',
    'Cheetah',
    'Honey, I Shrunk the Kids',
    'Who Framed Roger Rabbit',
    'Willow',
    'Benji the Hunted',
    'The Christmas Star',
    'Flight of the Navigator',
    'The Great Mouse Detective',
    'Fuzzbucket',
    'One Magic Christmas',
    'The Journey of Natty Gann',
    'The Black Cauldron',
    'Return to Oz',
    'TRON',
    'The Fox and the Hound',
    'The Great Muppet Caper',
    'Amy',
    'The Ghosts of Buxley Hall',
    'Herbie Goes Bananas',
    'The Black Hole',
    'Unidentified Flying Oddball',
    'The Apple Dumpling Gang Rides Again',
    'The Muppet Movie',
    'The Cat from Outer Space',
    'Return from Witch Mountain',
    'Candleshoe',
    'Petes Dragon',
    'Herbie Goes to Monte Carlo',
    'The Rescuers',
    'The Many Adventures of Winnie the Pooh',
    'The Shaggy D.A.',
    'Treasure of Matecumbe',
    'Gus',
    'The Apple Dumpling Gang',
    'Escape to Witch Mountain',
    'The Strongest Man in the World',
    'The Castaway Cowboy',
    'The Bears and I',
    'Herbie Rides Again',
    'Robin Hood',
    'Snowball Express',
    'The Biscuit Eater',
    'Justin Morgan Had a Horse',
    'Bedknobs and Broomsticks',
    'The Million Dollar Duck',
    'The Barefoot Executive',
    'The Aristocats',
    'The Computer Wore Tennis Shoes',
    'Blackbeards Ghost',
    'The Jungle Book',
    'The Adventures of Bullwhip Griffin',
    'The Ugly Dachshund',
    'That Darn Cat!',
    'The Sound of Music',
    'Those Calloways',
    'Emil and the Detectives',
    'Mary Poppins',
    'The Sword in the Stone',
    'The Incredible Journey',
    'Almost Angels',
    'The Prince and the Pauper',
    'Greyfriars Bobby: The True Story of a Dog',
    'The Parent Trap',
    'The Absent Minded Professor',
    '101 Dalmatians',
    'Swiss Family Robinson',
    'Pollyanna',
    'Journey to the Center of the Earth',
    'Darby OGill and the Little People',
    'The Shaggy Dog',
    'Sleeping Beauty',
    'The Sign of Zorro',
    'White Wilderness',
    'Old Yeller',
    'Perri',
    'Secrets of Life',
    'Davy Crockett and the River Pirates',
    'The African Lion',
    'Lady and the Tramp',
    'Davy Crockett: King of the Wild Frontier',
    '20,000 Leagues Under the Sea',
    'The Vanishing Prairie',
    'The Living Desert',
    'Peter Pan',
    'The Story of Robin Hood and His Merrie Men',
    'Alice in Wonderland',
    'Treasure Island',
    'Cinderella',
    'The Adventures of Ichabod and Mr. Toad',
    'Melody Time',
    'Miracle on 34th Street',
    'Bambi',
    'Dumbo',
    'The Reluctant Dragon',
    'Fantasia',
    'Swiss Family Robinson',
    'Pinocchio',
        'Snow White and the Seven Dwarfs']

function createSlots (ring) {
	
	var slotAngle = 360 / SLOTS_PER_REEL;

	var seed = getSeed();

	for (var i = 0; i < SLOTS_PER_REEL; i ++) {
		var slot = document.createElement('div');
		
		slot.className = 'slot';

		// compute and assign the transform for this slot
		var transform = 'rotateX(' + (slotAngle * i) + 'deg) translateZ(' + REEL_RADIUS + 'px)';

		slot.style.transform = transform;

		// setup the number to show inside the slots
        // the position is randomized to 
        
        //var content = $(slot).append('<img src="' + (images[i]) + '/>"');
        var content = $(slot).append('<img src="'+ images[i] + '">');
		// add the poster to the row
		ring.append(slot);
	}
}

function getSeed() {
	// generate random number smaller than 13 then floor it to settle between 0 and 12 inclusive
	return Math.floor(Math.random()*(SLOTS_PER_REEL));
}

function spin(timer) {
	//var txt = 'seeds: ';
	for(var i = 1; i < 6; i ++) {
		var oldSeed = -1;
		/*
		checking that the old seed from the previous iteration is not the same as the current iteration;
		if this happens then the reel will not spin at all
		*/
		var oldClass = $('#ring'+i).attr('class');
		if(oldClass.length > 4) {
			oldSeed = parseInt(oldClass.slice(10));
			console.log(oldSeed);
		}
		var seed = getSeed();
		while(oldSeed == seed) {
			seed = getSeed();
		}

		$('#ring'+i)
			.css('animation','back-spin 1s, spin-' + seed + ' ' + (timer + i*0.5) + 's')
			.attr('class','ring spin-' + seed);
	}

	console.log('=====');
}

$(document).ready(function() {

	// initiate slots 
 	createSlots($('#ring1'));
 	createSlots($('#ring2'));
 	createSlots($('#ring3'));
 	createSlots($('#ring4'));
 	createSlots($('#ring5'));
 	// hook start button
 	$('.go').on('click',function(){
 		var timer = 2;
         spin(timer);
         var randomMovieNum = Math.floor(Math.random() * movies.length)
    var randomMovie = movies[randomMovieNum]
    $("#test").text(randomMovie)
    var randomRuleNum = Math.floor(Math.random() * rules.length)
    var randomRule = rules[randomRuleNum]
    rules.splice(randomRuleNum, 1)
    $("#rule1").text(randomRule)
    var randomRuleNum = Math.floor(Math.random() * rules.length)
    var randomRule = rules[randomRuleNum]
    rules.splice(randomRuleNum, 1)
    $("#rule2").text(randomRule)
    var randomRuleNum = Math.floor(Math.random() * rules.length)
    var randomRule = rules[randomRuleNum]
    rules.splice(randomRuleNum, 1)
    $("#rule3").text(randomRule)
    var randomRuleNum = Math.floor(Math.random() * rules.length)
    var randomRule = rules[randomRuleNum]
    rules.splice(randomRuleNum, 1)
    $("#rule4").text(randomRule)
    var randomRuleNum = Math.floor(Math.random() * rules.length)
    var randomRule = rules[randomRuleNum]
    rules.splice(randomRuleNum, 1)
    $("#rule5").text(randomRule)
 	})
 });